### ISSUE TITLE
Crash on 24.1.0.0

### ISSUE THREAD

**Issue by kakai248** [Gericop/Android-Support-Preference-V7-Fix#29] opened 2016-07-20 19:08 UTC
I'm seeing a crash on a user. It's a Note 3 with Android 4.4.2. It seems it's because of the reflection not finding the fields? I can't reproduce this on my Nexus 5.

Here's the stacktrace:

```
Fatal Exception: java.lang.NullPointerException
       at com.takisoft.fix.support.v7.preference.PreferenceGroupAdapter.getReflectedIds(Unknown Source)
       at com.takisoft.fix.support.v7.preference.PreferenceGroupAdapter.getReflectedIds(Unknown Source)
       at com.takisoft.fix.support.v7.preference.PreferenceGroupAdapter.onCreateViewHolder(Unknown Source)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(Unknown Source)
       at android.support.v7.widget.RecyclerView$Recycler.clear(Unknown Source)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.hasMore(Unknown Source)
       at android.support.v7.widget.LinearLayoutManager.generateDefaultLayoutParams(Unknown Source)
       at android.support.v7.widget.LinearLayoutManager.generateDefaultLayoutParams(Unknown Source)
       at android.support.v7.widget.LinearLayoutManager.findViewByPosition(Unknown Source)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(Unknown Source)
       at android.support.v7.widget.RecyclerView.dispatchLayout(Unknown Source)
       at android.support.v7.widget.RecyclerView.onLayout(Unknown Source)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15648)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2245)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1967)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1199)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6383)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:573)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5293)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Gericop** [comment] 2016-07-20 20:39
Yeah, this definitely looks like a reflection problem. I wonder what can cause this as there were no changes to the preference part of the support library...

**Comment by Gericop** [comment] 2016-07-20 20:59
I guess the fields are in place, but probably something in the parent class happens before the initialization of the fields and it tries to use them.

I have an idea to try and resolve them later, but I don't have a device I could test it on (none of the emulators nor my devices produce this bug).

**Comment by Gericop** [comment] 2016-07-20 21:07
I committed it, if you could test it, that'd be awesome!

**Comment by kakai248** [comment] 2016-07-20 23:32
Thanks for the fast response! I'll reach the user and ask him to test.

**Comment by Gericop** [comment] 2016-07-21 00:34
So, it's now on jcenter too. Look for the version number **24.1.0.1**.

**Comment by kakai248** [comment] 2016-07-21 16:10
I contacted the user and sent him an APK with the new version of the preferences. Still crashes. Same stacktrace.

Looking at the code it could fail in 3 different ways:

1. The for doesn't execute once
2. The if evaluates false everytime
3. getDeclaredField returns null

I can't reproduce this in any way, don't know how to debug the problem. There's also so much I can ask the user to test. Really weird issue.

**Comment by Gericop** [comment] 2016-07-21 20:35
I'll try to reproduce it on AWS Device Farm. It has a 4.4.2 Note 3 device, so hopefully it will crash there too.

**Comment by Gericop** [comment] 2016-07-22 02:51
Haven't tried it yet, but seems like Google has released v24.1.1 of the support library (it's not on their [revision history](https://developer.android.com/topic/libraries/support-library/revisions.html) page at the time of writing this comment).

**Comment by Gericop** [comment] 2016-07-22 14:22
Well, I tested 24.1.0.1 on the AWS Device Farm's Note 3 with 4.4.2 and no crash happened.

**Comment by kakai248** [comment] 2016-07-22 14:33
I guess it could be because of Xposed. I really don't know. I'll stay in 23.4.0.5.

**Comment by Gericop** [comment] 2016-07-22 15:18
I'd recommend against that as eventually you will probably have to use the 24 versions anyways.

If your user uses Xposed, that's basically out of anyone's reach. Anything that interferes with the Android system is a hazard to any application. I don't know the Xposed internals but if it overrides reflections by changing the name of the fields, that's just wtf.

**Comment by Mygod** [comment] 2016-07-22 15:36
Xposed is like system hooks. Just ignore those.

**Comment by Gericop** [comment] 2016-07-22 15:47
It's interesting though. If I could grab that device, I'd check the reflection things, like what's the name of the fields / classes being resolved.

**Comment by kakai248** [comment] 2016-07-22 21:12
Yeah, eventually I'll have to update. It's not a must right now because I was only doing it for the preference category bottom margin.

It only happens to this one user, but if I update it, it completely kills the settings for him as he can't open anything at all.

And 24.1.1 doesn't seem to fix the problem. [The patch notes are out](https://developer.android.com/topic/libraries/support-library/revisions.html).

**Comment by Gericop** [comment] 2016-07-22 21:16
I can create a quickfix that makes it fall back to the original implementation when the reflection doesn't work, but that means no padding fix until the guys at Google fix it.

**Comment by Gericop** [comment] 2016-07-23 16:33
So, the new version (24.1.1.0) is available on gradle. It contains the aforementioned quickfix so if you want to use v24 without crashing that user, he/she won't encounter now the crash but see the non-padding-fixed version of the preferences.

**Comment by Gericop** [comment] 2016-08-18 02:56
v24.2.0.0 has been released, update your gradle file:
```gradle
compile 'com.takisoft.fix:preference-v7:24.2.0.0'
```

If you can, please check whether the bug still persists.

**Comment by kakai248** [comment] 2016-08-18 11:34
Ah sorry, I totally forgot about this. Will update and ask the user if everything is okay.

**Comment by kakai248** [comment] 2016-08-23 15:55
Seems to be working fine. When it is going to crash it ignores the margin and works fine. Thanks!

**Comment by Gericop** [comment] 2016-08-23 16:26
Yes, because the new one falls back to the original (paddingless) implementation on failure. Hopefully Google fixes the official lib soon...

**Closed by Gericop** 2016-08-23 16:26 UTC
Labels: bug

**Comment by j05u3** [comment] 2016-08-23 21:03
This happened also to me on a sony xperia with android 4.4.4 and version 24.1.0.1 
But I noticed that without proguard it worked fine.
